apiVersion: v1
kind: Pod
metadata:
  name: devboard-frontend
  namespace: devboard
spec:
  containers:
  - name: devboard-frontend
    image:  vaibhavmane09/devboard-frontend
    ports:
    - containerPort: 4173


