apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: devboard
  labels:
    app: devboard-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-postgres
  template:
    metadata:
      labels:
        app: devboard-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: devboard-configmap
                key: POSTGRES_USER
          
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devboard-secrets
                key: POSTGRES_PASSWORD

          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: devboard-secrets
                key: POSTGRES_DB

        volumeMounts:
          - name: init
            mountPath: /docker-entrypoint-initdb.d
            readOnly: true

      volumes:
        - name: init
          configMap:
            name: postgres-init 