# Stage1 : Builder stage : Used to build the package & app

FROM node:24 AS builder

# creats a fildern for code to stay & make it as present working directory
WORKDIR /app

#copies the code from host to container
COPY . .

#install the dependencies 
RUN npm install

# this will create /dist file where  all the node packeage available
RUN npm run build 


# ----------- stage 1 done------------------

#stage 2 - RUNNER use to run the application from the builder stage 

FROM node:24-alpine AS runner 

WORKDIR /app

COPY package.json .

RUN npm install -g vite

COPY --from=builder /app/dist ./dist

CMD ["npm", "run", "dev", "preview", "--", "--host", "0.0.0.0", "--port", "4174"]

# whenever you are having /dist file then we have to use 'preview' while running 
