# this docker file is for UI only, it will give you UI not entire application 


# bring the base images 

FROM node:24

#create a folder where code can stay
WORKDIR /app

#copy the code from host machine to container 
COPY . .

#install the required dependencies 
RUN npm install 

# expose the port for decumentation purpose 
EXPOSE 4173

# run the application 
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4173"]
