# stage 1 : Builder stage 

FROM golang:1.22-alpine AS builder

WORKDIR /app

# download deps first
COPY go.mod go.sum ./
RUN go mod download

# copy source & build a fully static binary
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
	-ldflags="-w -s" \
	-o devboard-backend .


# --------- stage 2: runner/production --------

FROM scratch AS runner

#copy SSL cert

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# copy compiled binary from builder
COPY --from=builder /app/devboard-backend /devboard-backend

USER 10001:10001

EXPOSE 8080

ENTRYPOINT ["/devboard-backend"]
