# Goal : To deploy the built images from the CI steps once the CI workflow is succeedded 

name: CD

on:
    #workflow_run:
    #    workflows: ['CI']
    #    types: [completed]
    #    branches:
    #        - 'advanced'
    workflow_call:
        
jobs:
    deploy:
        runs-on: self-hosted
        steps: 
            - name: Code checkout
              uses: actions/checkout@v7

            - name: Cpy example.env to main .env
              run: cp .env.example .env 

            - name: Docker login
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Deploy the containers with docker compose
              run: | 
                docker compose pull
                docker compose up -d