# Goal - I've to lint, build, test the code for frontend & backend 
# then push the images to docker hub

name: CI

on:
    push:
        branches: [advanced]

jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Setup-Node Js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json

            - name: Install npm packages
              working-directory: frontend
              run: npm ci

            - name: Run linter
              working-directory: frontend
              run: npm run lint

            - name: Run test
              working-directory: frontend
              run: npm run test
            
            - name: Docker login
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v7
              with:
                context: ./frontend
                file: frontend/Dockerfile.multistage
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-frontend:latest


    backend:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Setup go 
              uses: actions/setup-go@v6
              with:
                go-version: '1.23'
                go-version-file: 'backend/go.mod'
                check-latest: false
                cache: true
                # Path to dependency files for caching
                cache-dependency-path: 'backend/go.sum'

            - name: Run go formatter
              working-directory: backend
              run: go fmt

            - name: Run GO vetter
              working-directory: backend
              run: go vet

            - name: Run test 
              working-directory: backend
              run: go test
            
            - name: Docker login
              uses: docker/login-action@v4
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v7
              with:
                context: ./backend
                file: backend/Dockerfile.multistage
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-backend:latest

    deploy:
        needs: [frontend,backend]
        uses: ./.github/workflows/cd.yml
        secrets: inherit