# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [advanced]

jobs:

    # Code Stage (with Shift left)
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # Secret Scanning
    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    # Dependency Checks
    dependency-checks:
        uses: ./.github/workflows/dependancy-scan.yml

    # Docker Checks
    docker-scan:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit 